shotgunsoftware/tk-nuke

engine.py
When a project file is opened via File->Open or File->Recent Files, the engine attempts to extract a new context from that project and change to it.
=> #36608: Adds an event callback that attempts a context change on project open.

engine.py
Only disabling parenting for Nuke 7 since it is the only version crashing on exit with parenting
=> #36966 Only Disable Parenting in Nuke 7

python/tk_nuke/__init__.py, startup/menu.py
The combination of onScriptLoad plus calling the same logic from the menu.py handles setting the context both for script load and file->new actions. This reduces the number of events we're handling.
=> #37034: Switches to using onScriptLoad rather than onCreate to handle context setting.

engine.py, hooks/filter_dependencies.py, info.yml
Added implementation for the following engine methods:
* get_session_path() - Returns the absolute file path of the nuke script if saved, else returns an empty string.
* get_session_dependencies() - Returns the file path dependencies of the current nuke script for the global file frame range. 
Linked with: https://github.com/shotgunsoftware/tk-core/pull/544
=> SPLAT-83: Added methods to retrieve script path and dependencies.

hooks/tk-multi-publish2/basic/nuke_update_flame_clip.py
There are a number of behavioral changes included, as documented below.
**Input acceptance:**
* If tk-nuke-writenode is in use, only items associated with an instance of that app will be accepted.
* If the writenode app is NOT in use, then all image sequence items will be accepted.
**Clip lookup behavior:**
* If the publish plugin is configured with a "Flame Clip Template" we will attempt to find a clip file matching that template.
* If there is no template configured or the clip file does not exist in the location that the template expects it to, we look for a PublishedFile entity linked to the item's context's entity (most likely a Shot) that matches the PublishedFileType associated with Flame OpenClip publishes.
**Current caveats:**
* We're modifying a PublishedFile's file on disk in …
=> For #46098: First pass at Flame OpenClip updating when no templates exist.

engine.py
This resolves an issue with Nuke 9.x that caused the engine to fail on initialization.
=> For SG-2631: Makes the host_info property exception safe.

engine.py
Importing QtWebEngineWidgets from PySide2 on Windows can cause an unrecoverable deadlock in some cases. Since we do not make use of it in any of the out-of-the-box Toolkit bundles or tk-core, we can safely skip importing that submodule. Any clients that require its use can import it directly from PySide2.
=> For SG-4782: Skips importing the web engine widgets submodule when on Windows

hooks/tk-multi-publish2/basic/nuke_publish_script.py, hooks/tk-multi-publish2/basic/nukestudio_publish_project.py
Makes sure the folder for the work file to be saved into exists before it tells Nuke or Nuke Studio to save the file.
=> SG-6429 ensure folder exists on publish save

hooks/tk-multi-publish2/basic/nuke_update_flame_clip.py
The assumptions we made concerning the structure of the portion of a Flame openclip around video tracks were flimsy. To correct some issues we're seeing in beta and head off any future problems with the Flame<->Nuke workflow, the logic here has been tweaked to bring it in line what what the Flame engineers are expecting from our implementation.
=> SG-6781: Updates logic around parsing Flame openclip files during publish.

engine.py
Doing `engine.context_change()` while running a `nuke -t` session produces the error:
> 'NoneType' object has no attribute 'create_menu'
Checking for has_ui before attempting to create menu fixes that.
=> in on_context_change() add has_ui check

python/tk_nuke/menu_generation.py
added the ability to specify hotkeys in the tk-nuke.yml config file like this:
```yaml
settings.tk-nuke.shot_step:
menu_favourites:
- {app_instance: tk-multi-workfiles2, name: File Open..., hotkey: "ctrl+o"}
- {app_instance: tk-multi-snapshot, name: Snapshot..., hotkey: "alt+shift+s"}
```
=> added ability to set hotkeys in the tk-nuke.yml settings file.

python/tk_nuke/context.py, python/tk_nuke/menu_generation.py
A small bug fix for an issue where it errored trying to display the error menu in Nuke Studio.
=> SG-11232 Small bug fix for error menu generation in Nuke Studio

python/tk_nuke/__init__.py
Reverses a change in v0.12.1 to make the `sgtk_on_load_callback` public again, as it is called from out side the module.
https://github.com/shotgunsoftware/tk-nuke/blob/v0.12.2/plugins/basic/Python/tk_nuke_basic/plugin_bootstrap.py#L334
=> SG-14088 makes sgkt_on_load_callback public

classic_startup/init.py, classic_startup/menu.py, engine.py
We were popping off of sys.path after bootstrapping, which meant we removed the last thing appended to sys.path that might have occurred during engine init instead of what we intended to clean up. We now filter out the specific path we added prior to bootstrapping instead.
=> SG-14409: Cleans up sys.path responsibly after bootstrapping

engine.py, python/tk_nuke_qt/panels.py
A small qss tweak in the shotgunpanel app resolved the crashing problems on OSX, but the issue persisted despite that on Windows and Linux. That crash in Nuke 12 does not appear to be tied to the qss itself, but the fact that ANY qss is being applied at the exact moment that it is in our panel-specific logic in tk-nuke.
This fix works and has no visible impact for the user. We're just deferring the application of the qss until Qt has a chance to finish whatever it's doing at that moment.
=> SG-14164: Resolves shotgunpanel crashing in Nuke 12.

engine.py
Fix for Nuke hanging when an app produces a lot of output and the script editor is open.
=> SG-18819 Fix for locking up of Nuke when logging.

engine.py
NEW FIX DESCRIPTION: The run_at_startup commands are executed while the splashscreen is visited, which is when nuke informs us that the GUI is ready. Unfortunately, it appears that calling async_execute_to_main_thread will lock up at that point of the startup process. I've tried reimplementing it in tk-core with `QMetaObject`, just like  `execute_from_main_thread`, but it still locked up. This is unexpected as a `Qt.QueueConnection` is expected to be non-blocking. What I suspect is happening here is that the main thread has a lock the list of events in the main thread and is not relinquishing it for some reason and our background thread is stuck waiting for the main thread to relinquish it so it can send it's signal.
In the end, I ended up doing something else: postponing the launch of …
=> SG-19954: Fixes a freeze when launching Nuke v11.3 with debugging logging on.

info.yml
It seems we forgot to update the requires core version when we did the work to replace support email by support url
=> updated requires core version

tests/test_startup.py
This PR fixes the Python 3.9 tests in Azure, using a new mocked implementation of glob._iterdir() method for Python >=3.9.
=> SG-25108 Fix Python 3.9 Azure Pipelines Tests for tk-nuke

.pre-commit-config.yaml, README.md, engine.py, hooks/tk-multi-publish2/basic/nuke_update_flame_clip.py, python/tk_nuke/context.py, python/tk_nuke/menu_generation.py, python/tk_nuke_qt/panels.py, tests/test_startup.py
This PR includes the actions to remove Python 2.6 support in toolkit:
- Remove python 2.6 badges
- Update setup.py to drop support for 2.6
- Update the documentation and the developer.shotgunsoftware.com doc site
=> SG-20925 Formalize the deprecation of python 2.6 support in toolkit

info.yml, python/tk_nuke/__init__.py
This originally comes from this [PR ](https://github.com/shotgunsoftware/tk-nuke/pull/97), and aims to introduce a new engine setting that avoids the ShotGrid menu from being disabled when for example someone opens a file with Nuke's File --> Open, that does not reside in any known project path, allowing users to retain the Project context enabled so that the user can use the shotgrid workfiles app to save the current file into the pipeline.
Fixes #97
=> SG-30710 Add Setting For Keeping Project Context If Could Not Resolve sgtk From Path

engine.py, info.yml
_Sgtk_ does not make sense anymore since #104 
- Rename the `use_sgtk_as_menu_name` setting to `use_short_menu_name`
- Rename the short menu name "**Sgtk**" to "**FPTR**"
=> SG-35286 Rename the short menu name from "Sgtk" to "FPTR"

engine.py
It's probably bad practice to permanently change hiero's log level just to print a sg debug log.
HieroPlayer doesn't have a frameserver, so the warning in this file fires every second : /apps/foundry/nuke/Nuke12.2v4/pythonextensions/site-packages/hiero/ui/FnStatusBar.py
To prevent this, we need to revert hiero's log level to what it was before we emit a debug level message.
=> SG-37311 Update engine.py

README.md, engine.py, info.yml, startup.py, tests/test_startup.py
Add support for Nuke 16
- Update newest supported version from `15.0+` to `16+` 
- Update oldest compatible version from `7.0v10` to `13.0v1`. Older versions are shipping Python 2.
- Update badges
- Update core version requirement to v0.22.3 to support Nuke 16
=> SG-38376 Add support for Nuke 16
